# Why use NumPy ?

Python lists are flexible but **slow for numerical computing** because they:

* **Store elements as pointers** instead of a **continuous block of memory**.
* **Lack vectorized operations**, relying on **loops instead**.
* **Have significant overhead** due to **dynamic typing**.

---

## NumPy's Superpowers

* ⚡ **Faster than Python lists** *(C-optimized backend)*
* 💾 **Uses less memory** *(efficient storage)*
* 🔄 **Supports vectorized operations** *(no explicit loops needed)*
* 📊 **Has built-in mathematical functions*


In [15]:
#------------ Adding two lists -------------

import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", np.round(end - start,5))

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", np.round(end - start,5))

print("Python list size:", sys.getsizeof(list2) * len(list2), "bytes")
print(f"Numpy array total memory occupied : {arr2.nbytes} bytes")


Python list addition time: 0.06611
NumPy array addition time: 0.0157
Python list size: 8000056000000 bytes
Numpy array total memory occupied : 8000000 bytes


#Creating NumPy Arrays
##🔹 NumPy stores data in a contiguous memory block, making access faster than lists.
##🔹 shape shows the dimensions of an array.

In [8]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


# Memory Efficiency – NumPy vs. Lists
## Let's check memory consumption.

In [13]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


# Vectorization – No More Loops!
* NumPy avoids loops by applying operations to entire arrays at once using SIMD (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a CPU-level optimization provided by modern processors.

In [22]:
#List vs Numpy
l = [1,2,3,4]
v_array = np.array(l)

#Squarring list using loop
l = [x ** 2 for x in l]

#Vectorization comes in handy
v_array = v_array ** 2

#Displaying the results
print("List : ",l)
print("np array : ",v_array)

List :  [1, 4, 9, 16]
np array :  [ 1  4  9 16]


## Summary
* NumPy is faster than Python lists because it is optimized in C.
* It consumes less memory due to efficient storage.
* It provides vectorized operations, removing the need for slow loops.
* Essential for data science and machine learning workflows.

 # -------------------------------------------------------------------------------


## Creating Arrays from Scratch:

In [23]:
print(np.zeros((3, 3)))     # 3x3 array of zeros
print(np.ones((2, 4)))      # 2x4 array of ones
print(np.full((2, 2), 7))   # 2x2 array filled with 7
print(np.eye(4))            # 4x4 identity matrix
print(np.arange(1, 10, 2))  # [1, 3, 5, 7, 9] (like range)
print(np.linspace(0, 1, 5)) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]


## 2. Checking Array Properties


In [26]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)      # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)        # 6 → total elements
print("Dimensions:", arr.ndim)  # 2 → 2D array
print("Data type:", arr.dtype)  # int64 (or int32 on Windows)
print("Memory occupied : ",arr.nbytes,"bytes") #Memory occupied

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64
Memory occupied :  48 bytes


## 3. Changing Data Types

In [31]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

float32
[1 2 3]


## 4. Reshaping and Flattening Arrays

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


# -------------        Indexing and slicing       ----------------

## Indexing (Same as Python Lists)

In [39]:
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40
print(arr[::-1]) #Reversed array

10
40
[40 30 20 10]


## Slicing (Extracting Parts of an Array)

In [45]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

#Want a copy ?
c = arr.copy()
c[0] = 1000
print(arr)
print(c)

'''Slicing returns a view, not a copy! Changes affect the original array.**
This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

Why does this happen?

Memory Efficiency: Avoids unnecessary copies, making operations faster and saving memory.
Performance: Enables faster access and manipulation of large datasets without duplicating data.


Use .copy() if you need an independent copy.'''

[20 30 40]
[10 20 30]
[10 30 50]
[ 10 999  30  40  50]
[ 10 999  30  40  50]
[1000  999   30   40   50]


'Slicing returns a view, not a copy! Changes affect the original array.**\nThis might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.\n\nWhy does this happen?\n\nMemory Efficiency: Avoids unnecessary copies, making operations faster and saving memory.\nPerformance: Enables faster access and manipulation of large datasets without duplicating data.\n\n\nUse .copy() if you need an independent copy.'

## 6. Fancy Indexing & Boolean Masking
Fancy Indexing (Select Multiple Elements)

In [50]:
#Fancy indexing
a = np.array([1,2,3,4,5,6])
i = [0,-1,3]
print(a[i])

#Bolean Masking for even numbers in array of range 1 to 100
m = np.arange(101)

mask = m % 2 == 0

print("Original array : ",m)
print("Array of even numbers : ",m[mask])

[1 6 4]
Original array :  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
Array of even numbers :  [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



## Summary
* NumPy arrays are faster, memory-efficient alternatives to lists.
* You can create arrays using np.array(), np.zeros(), np.ones(), etc.
* Indexing & slicing allow efficient data manipulation.
* Reshaping & flattening change array structures without copying data.
* Fancy indexing & boolean masking help filter and access specific data.

## Exercises for Practice
* Create a 3×3 array filled with random numbers and print its shape.
* Convert an array of floats [1.1, 2.2, 3.3] into integers.
* Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
* Reshape a 1D array of size 9 into a 3×3 matrix.
* Use boolean masking to filter numbers greater than 50 in an array.

# ----------------- Multidimensional Indexing and Axis -----------------

##1. Understanding Axes in NumPy
Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.

For example:

1D array → 1 axis (axis 0)
2D array → 2 axes (axis 0 = rows, axis 1 = columns)
3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [51]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* Axis 0 (rows) → Operations move down the columns.
* Axis 1 (columns) → Operations move across the rows.


In [52]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


# ---------------------- Data Types in NumPy -----------------------


Here is your **same content with cleaner styling and structure** (content unchanged):

---

# 1. Introduction to NumPy Data Types

NumPy arrays are **homogeneous**, meaning that they can only store **elements of the same type**.
This is different from **Python lists**, which can hold **mixed data types**.

NumPy supports various **data types (also called dtypes)**, and understanding them is **crucial for optimizing memory usage and performance**.

---

## Common Data Types in NumPy

* **`int32`, `int64`**
  Integer types with **different bit sizes**.

* **`float32`, `float64`**
  Floating-point types with **different precision**.

* **`bool`**
  Boolean data type.

* **`complex64`, `complex128`**
  Complex number types.

* **`object`**
  For storing **objects** *(e.g., Python objects, strings)*.

---

## Checking the Data Type of an Array

You can check the **dtype of a NumPy array** using the **`.dtype` attribute**.


In [58]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int64 (or int32 depending on the system)

# Changing data type
arr = np.array([1.5, 2.7, 3.9])
print(arr.dtype)  # Output: float64

arr_int = arr.astype(np.int32)  # Converting float to int
print(arr_int)    # Output: [1 2 3]
print(arr_int.dtype)  # Output: int32

#Downcasting to save memory
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)  # Output: [1000000 2000000 3000000]
print(arr_small.dtype)  # Output: int32

#Memory Usage
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

#String data type
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr)

#Complex numbers
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

#Object dtype
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

int64
float64
[1 2 3]
int32
[1000000 2000000 3000000]
int32
24
12
['apple' 'banana' 'cherry']
[1.+2.j 3.+4.j 5.+6.j]
[{'a': 1} list([1, 2, 3]) 'hello']


## Summary:
* NumPy arrays are homogeneous, meaning all elements must be of the same type.
* Use .astype() to change data types and optimize memory and performance.
* The choice of data type affects memory usage, performance, and precision.
* Be mindful of complex numbers and object data types, which can increase memory usage and reduce performance.

# ------------------- Broadcasting in NumPy -------------------

##  Hands-on: Applying Broadcasting to Real-World Scenarios

In [59]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


## Summary:
* Loops are slow because Python's interpreter adds overhead, making iteration less efficient.
* Vectorization allows you to apply operations to entire arrays at once, greatly improving performance by utilizing NumPy’s optimized C backend.
* Broadcasting enables operations between arrays of different shapes by automatically stretching the smaller array to match the shape of the larger array, without creating additional copies.
Real-world use: Broadcasting can be used in data science tasks, such as normalizing datasets, without sacrificing memory or performance.

# ----------- Built in Mathematical Functions in NumPy ------------
Here are some common NumPy methods that are frequently used for statistical and mathematical operations:

Here is your **same content with improved styling and readability** (no wording changes):

---

# NumPy Mathematical & Statistical Functions

### Mean

**`np.mean()`** – Compute the mean (average) of an array.

```python
np.mean(arr)
```

---

### Standard Deviation

**`np.std()`** – Compute the standard deviation of an array.

```python
np.std(arr)
```

---

### Variance

**`np.var()`** – Compute the variance of an array.

```python
np.var(arr)
```

---

### Minimum Value

**`np.min()`** – Compute the minimum value of an array.

```python
np.min(arr)
```

---

### Maximum Value

**`np.max()`** – Compute the maximum value of an array.

```python
np.max(arr)
```

---

### Sum of Elements

**`np.sum()`** – Compute the sum of all elements in an array.

```python
np.sum(arr)
```

---

### Product of Elements

**`np.prod()`** – Compute the product of all elements in an array.

```python
np.prod(arr)
```

---

### Median

**`np.median()`** – Compute the median of an array.

```python
np.median(arr)
```

---

### Percentile

**`np.percentile()`** – Compute the percentile of an array.

```python
np.percentile(arr, 50)  # For the 50th percentile (median)
```

---

### Index of Minimum Value

**`np.argmin()`** – Return the index of the minimum value in an array.

```python
np.argmin(arr)
```

---

### Index of Maximum Value

**`np.argmax()`** – Return the index of the maximum value in an array.

```python
np.argmax(arr)
```

---

### Correlation Coefficient Matrix

**`np.corrcoef()`** – Compute the correlation coefficient matrix of two arrays.

```python
np.corrcoef(arr1, arr2)
```

---

### Unique Elements

**`np.unique()`** – Find the unique elements of an array.

```python
np.unique(arr)
```

---

### Differences Between Elements

**`np.diff()`** – Compute the n-th differences of an array.

```python
np.diff(arr)
```

---

### Cumulative Sum

**`np.cumsum()`** – Compute the cumulative sum of an array.

```python
np.cumsum(arr)
```

---

### Evenly Spaced Numbers

**`np.linspace()`** – Create an array with evenly spaced numbers over a specified interval.

```python
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10
```

---

### Natural Logarithm

**`np.log()`** – Compute the natural logarithm of an array.

```python
np.log(arr)
```

---

### Exponential

**`np.exp()`** – Compute the exponential of an array.

```python
np.exp(arr)
```

---

✅ **Summary**

These methods are used for performing **mathematical and statistical operations with NumPy**.
